asciidoc/sdpi-supplement-issues.adoc, asciidoc/sdpi-supplement.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume3/tf3-ch-8.7.3-physiologic-monitor.adoc
Addressed all PUB TODO's
Commented out a #TODO highlight that was still remaining
=> Removal of PUB TODOs and Formatting Updates

asciidoc/volume0/tf0-ch-9-copyrights.adoc
=> Moved 9.5 to 9.1.5

asciidoc/volume2/gateways/tf2-ch-b-gateway-pid-mapping.adoc, asciidoc/volume2/gateways/tf2-ch-b-gateway-private-mdc-mapping.adoc
#58 updated note 
#9 added requirement
=> Private Code Section

asciidoc/plantuml/vol1-figure-sdpi-a-delegation-example-sequence-diagram.puml, asciidoc/plantuml/vol1-figure-sdpi-a-reporting-example-sequence-diagram.puml, asciidoc/plantuml/vol1-figure-sdpi-r-example-sequence-diagram.puml, asciidoc/plantuml/vol1-figure-sdpi-xc-example-sequence-diagram.puml
@ToddCooper I added Plant UML diagrams. Would add them to the corresponding profile sections?
=> #63 Provide PlantUML diagrams for profiles A, R and xC.

asciidoc/volume2/gateways/tf2-ch-b-gateway-msh-mapping.adoc
Closes #88
Updated R8118 (added comma before which)
None
=> Updated R8118 (added comma before which)

asciidoc/volume2/gateways/tf2-ch-b-gateway-dec.adoc
Reworked OBR-7 and OBR-8 mapping requirements.
None
=> Reworked OBR-7 and OBR-8 mapping requirements.

asciidoc/sdpi-supplement-intro.adoc, asciidoc/volume0/tf0-ch-a-actors.adoc, asciidoc/volume0/tf0-ch-d-glossary.adoc, asciidoc/volume0/tf0-main.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume2/dev-x-default-ses-secured-mode.adoc, asciidoc/volume2/dev-x-default-ses-unsecured-mode.adoc
Closes #68 , #107 
Reviewed and updated all comments from the issue that had "#fix" + the SES "shall" statement removal.
=> 68 general 1.0 updates from public comment

asciidoc/volume2/gateways/tf2-ch-b-gateway-pid-mapping.adoc
=> Added conditionality of R8102 to R8103 through R8109

asciidoc/volume2/gateways/tf2-ch-b-gateway-pv1-mapping.adoc
=> Added conditionality of R8111 to R8112 through R8116

asciidoc/volume2/gateways/tf2-ch-b-gateway-pv1-mapping.adoc
Closes (again) # 92
PR to revert previous change to R8112
=> Revert previous change to R8112

asciidoc/volume1/tf1-ch-12-sdpi-a.adoc
Corrected reference in 1:12.1.1-1 to the correct file name.
Closes # 
#135
=> Corrected SDPi-A PUML Example File

CHANGELOG.md, asciidoc/sdpi-supplement.adoc
=> Prepare release / bump version number to 1.0.1.

asciidoc/volume2/gateways/tf2-ch-b-gateway-dec.adoc
Fixed broken link to IHE PCD TF 2.
=> Fixed broken link to IHE PCD TF 2.

asciidoc/volume2/gateways/tf2-ch-b-gateway-acm.adoc, asciidoc/volume2/gateways/tf2-ch-b-gateway-dec.adoc, asciidoc/volume2/gateways/tf2-ch-b-gateway-obx3-mapping.adoc, asciidoc/volume2/gateways/tf2-ch-b-gateway-private-mdc-mapping.adoc
…ed "MDC" with "<<acronym_mdc>>".
Added mapping of coding system version in code mapping tables; replaced "MDC" with "<<acronym_mdc>>".
=> Added mapping of coding system version in code mapping tables

CHANGELOG.md, asciidoc/volume1/use-cases/tf1-ch-c-use-case-stad.adoc
=> #155 Add another 2 use case descriptions.

CHANGELOG.md, asciidoc/volume1/use-cases/tf1-ch-c-use-case-stad.adoc
=> #30 Forbid manual TS Service configuration

CHANGELOG.md, asciidoc/volume1/use-cases/tf1-ch-c-use-case-stad.adoc
=> #180 rephrase according to review comment from Max

CHANGELOG.md, asciidoc/sdpi-supplement-intro.adoc, asciidoc/sdpi-supplement-issues.adoc, asciidoc/sdpi-supplement.adoc, asciidoc/volume1/conformance-statements/tf1-ch-c-conformance-statement-ieee-11073-10207-2017.adoc, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc, asciidoc/volume1/use-cases/tf1-ch-c-60601-1-8.adoc, asciidoc/volume2/gateways/tf2-ch-b-gateway-dec.adoc, asciidoc/volume3/tf3-ch-8.3.2-biceps-content.adoc, asciidoc/volume3/tf3-ch-8.7.1-infusion-pump.adoc, asciidoc/volume3/tf3-ch-8.7.2-ventilator.adoc, asciidoc/volume3/tf3-ch-8.7.4-surgical.adoc, asciidoc/volume3/tf3-main.adoc
Moved R1542 and R1543 to the SDPi-P SES Effectiveness section.
Moved the two requirements from their "temporary" home in the STAD use case to the Effectiveness section of the 
* [x ] Pull Request Assignee
=> Reviewed Supplement for 1.0 Related Text

.ci/asciidoc-converter/src/main/kotlin/org/sdpi/asciidoc/extension/NumberingProcessor.kt, CHANGELOG.md
=> Fix appendix numbering issue in references

.ci/asciidoc-converter/src/main/kotlin/org/sdpi/asciidoc/extension/NumberingProcessor.kt, CHANGELOG.md
* Fix appendix numbering issue in references.
* #189 Add changelog entry.
IHE Publications comments to 1.1 Vol 0 & 1
=> Fix appendix numbering issue in references (#190)

CHANGELOG.md
=> Bump version in changelog.

asciidoc/volume2/gateways/tf2-ch-b-gateway-msh-mapping.adoc
Rewording R8101 to make clear that there shall be a new HL7 Message for each MDS.
=> Rewording R8101

asciidoc/volume2/gateways/tf2-ch-b-gateway-acm.adoc
Detailded mapping requirements for advisories.
=> 179 how is an advisory modelled contradictory definitions in a pkp and ihe acm

CHANGELOG.md, asciidoc/volume2/gateways/tf2-ch-b-gateway-dec.adoc
=> 233 obx 17 observation method mapping kpr

asciidoc/volume2/gateways/tf2-ch-b-gateway-pid-mapping.adoc
=> 24 sexgender mapping is incorrect

CHANGELOG.md, asciidoc/volume1/tf1-ch-2-overview.adoc
Updated the TF-1 Profiles Overview section to add a Scope of Application statement subsection.
=> 235 explicit sdpi scope statement

CHANGELOG.md, asciidoc/sdpi-supplement.adoc
Added HL7 recognition + PDF language + STU/TI vs. use it in products now!
Updated the Title Page per the Issue and added some Gemini explanatory text for STU/TI vs. product implementation.
=> Updated Title Page with additional HL7 focused content

asciidoc/volume0/tf0-ch-d-glossary.adoc
=> Proposed changes to glossary table to address issue #166

CHANGELOG.md, asciidoc/sdpi-supplement-intro.adoc, asciidoc/sdpi-supplement.adoc, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc, asciidoc/volume1/use-cases/tf1-ch-c-60601-1-8.adoc, asciidoc/volume3/tf3-ch-8.3.2-biceps-content.adoc, asciidoc/volume3/tf3-ch-8.7.1-infusion-pump.adoc, asciidoc/volume3/tf3-ch-8.7.2-ventilator.adoc, asciidoc/volume3/tf3-ch-8.7.4-surgical.adoc, asciidoc/volume3/tf3-main.adoc
=> Review 1.2.0

CHANGELOG.md
Just a version bump to 1.2.0 in the changelog
=> Bump version in CHANGELOG.md

asciidoc/volume2/gateways/tf2-ch-b-gateway-obx18-mapping.adoc, asciidoc/volume3/biceps-extension-provisions/tf3-ch-8.3.2.9.6-extension-equipment-identifier.adoc
Updated OBX-18 mapping to device identifier as described in tf3-ch-8.3.2.9.6-extension-equipment-identifier.
=> 195-mdsvmd-identification

asciidoc/volume2/dev-39/tf2-ch-a-mdpws-dev-39.adoc
Added message mapping for transaction DEV-39
=> #251 added message mapping for dev39

asciidoc/volume2/mdib-report-retrofit/tf2-ch-a-mdpws-mdib-report-retrofit.adoc
=> #259 Add requirement to enforce serialization of any notifications.

asciidoc/listings/vol3-clause-biceps-content-example-compound-metric.xml, asciidoc/volume3/biceps-content-module/tf3-ch-8.3.2.9.7-compound-metric-modelling.adoc, asciidoc/volume3/tf3-ch-8.3.2-biceps-content.adoc
Define the modelling and requirements for compound metrics.
=> Define the modelling and requirements for compound metrics.

asciidoc/volume2/tf2-ch-a-mdpws.adoc
=> #260 Add info regarding correctness of message excerpts.

CHANGELOG.md, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume1/use-cases/tf1-ch-c-60601-1-8.adoc
Update SDPi 1.2 per HL7 ballot comment resolutions for the JAN2024 ballot. 
NOTE:  Some ballot comment resolutions will take more than a single PR.
=> HL7 JAN2024 SDPi Ballot Issue Resolutions (Block #1)

CHANGELOG.md
=> Update changelog to contain all 1.3 tickets. (were missing)

CHANGELOG.md, asciidoc/sdpi-supplement-intro.adoc, asciidoc/sdpi-supplement.adoc, asciidoc/volume1/conformance-statements/tf1-ch-c-conformance-statement-ieee-11073-10207-2017.adoc, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc, asciidoc/volume1/use-cases/tf1-ch-c-60601-1-8.adoc, asciidoc/volume3/tf3-ch-8.3.2-biceps-content.adoc, asciidoc/volume3/tf3-ch-8.7.1-infusion-pump.adoc, asciidoc/volume3/tf3-ch-8.7.2-ventilator.adoc, asciidoc/volume3/tf3-ch-8.7.4-surgical.adoc, asciidoc/volume3/tf3-main.adoc
Addressed #282 changes.
Updated all release 1.2 (and related) release references to 1.3 (and related).  
=> Changed 1.2 to 1.3 throughout specification

CHANGELOG.md, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc, asciidoc/volume1/use-cases/tf1-ch-c-use-case-stad.adoc, asciidoc/volume2/dev-x-default-ses-secured-mode.adoc, asciidoc/volume2/dev-x-default-ses-unsecured-mode.adoc, asciidoc/volume2/tf2-ch-a-mdpws.adoc, asciidoc/volume3/tf3-ch-8.3.2-biceps-content.adoc
=> 272 hl7 2024 jan ses section title reference corrections

CHANGELOG.md, asciidoc/document-declarations.adoc, asciidoc/sdpi-supplement-intro.adoc, asciidoc/sdpi-supplement.adoc, asciidoc/volume0/tf0-ch-9-copyrights.adoc, asciidoc/volume0/tf0-ch-d-glossary.adoc, asciidoc/volume1/conformance-statements/tf1-ch-c-conformance-statement-ieee-11073-10207-2017.adoc, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc, asciidoc/volume1/tf1-ch-b-ref-standards-conformance.adoc, asciidoc/volume1/use-cases/tf1-ch-c-60601-1-8.adoc, asciidoc/volume1/use-cases/tf1-ch-c-use-cases.adoc, asciidoc/volume2/gateways/tf2-ch-b-gateway-dec.adoc, asciidoc/volume3/biceps-extension-provisions/tf3-ch-8.3.2.9.5-extension-gender.adoc, asciidoc/volume3/tf3-ch-8.3.2-biceps-content.adoc, asciidoc/volume3/tf3-ch-8.7.1-infusion-pump.adoc, asciidoc/volume3/tf3-ch-8.7.2-ventilator.adoc, asciidoc/volume3/tf3-ch-8.7.4-surgical.adoc, asciidoc/volume3/tf3-main.adoc
=> #284 Add variables for SDPi version string (short version number)

asciidoc/volume3/mdib-report-retrofit/tf3-ch-8.3.2.9-mdib-report-retrofit.adoc
Resolution of #291 
* [ x] Pull Request Assignee
=> changed message order in R1007

CHANGELOG.md, asciidoc/volume3/mdib-report-retrofit/tf3-ch-8.3.2.9-mdib-report-retrofit.adoc
=> Resolution implemented

CHANGELOG.md, asciidoc/volume2/dev-47/tf2-dev-47.adoc
=> 317 probematch behaviour potentially inconsistent

CHANGELOG.md, asciidoc/volume1/tf1-ch-b-ref-standards-conformance.adoc
=> Corrected some entries in "1:B.1 Referenced Standards" for consistency

CHANGELOG.md, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc
=> 264 hl7 2024 jan clarify fhir gateway actor support for multiple paradigms

CHANGELOG.md, asciidoc/volume0/tf0-ch-a-actors.adoc
=> 273 hl7 2024 jan resolve or remove tbd statements from text

CHANGELOG.md, asciidoc/volume1/tf1-ch-2-overview.adoc
A note was added to section 1:2.2 to indicate that the SES sections in the document are not intended to represent comprehensive risk management requirements and that implementers must ensure that appropriate RM processes have been completed.
=> SES Non-Comprehensive Note Added

CHANGELOG.md, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume1/tf1-ch-b-ref-standards-conformance.adoc
General rationale provided at the beginning of the section with scope statements for each of the three subsections.
NOTE:  Not added was anything related to the fact that it may change in the future if someone has a big idea and the energy to make the change.
=> Updated Rational for Bibliography subsections

CHANGELOG.md, asciidoc/sdpi-supplement-intro.adoc, asciidoc/volume0/tf0-ch-d-glossary.adoc, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume2/gateways/tf2-ch-b-gateway-acm.adoc
=> 269 hl7 2024 jan review ihe style conventions regarding numbers in text use of em dashes punctuation quotation marks etc

CHANGELOG.md, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc, asciidoc/volume2/tf2-ch-c-security.adoc, asciidoc/volume2/tf2-main.adoc
Added files for Volume 2 Appendix C Security Management Added references to TF-1C SES Security section.
Added a basic "empty" Appendix for security-related content.  Intent is that as content is identified and developed, it will be added to this appendix.
* [X ] Reviewer
=> Initial Addition of TF-2C

CHANGELOG.md, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc
=> 363 hl7 2025 jan typos and grammar

CHANGELOG.md, asciidoc/sdpi-supplement.adoc
=> Added in Foreword rationale for discontinuous section numbering

CHANGELOG.md, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc
=> Changed subsection order

CHANGELOG.md, asciidoc/sdpi-supplement-issues.adoc
=> Clarified status of open Issues and Topics of Interest

CHANGELOG.md, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc, asciidoc/volume2/tf2-ch-c-security.adoc
=> Clarified TLS 1.2 versus TLS 1.3 usage

CHANGELOG.md, asciidoc/sdpi-supplement-intro.adoc
=> Clarified TF-X acronym meaning

CHANGELOG.md, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume2/tf2-ch-b-gateways.adoc
=> Added description of SDC gateways

CHANGELOG.md, asciidoc/volume1/use-cases/tf1-ch-c-60601-1-8.adoc
=> Clarified technical confirmation versus operator confirmation

CHANGELOG.md, asciidoc/volume2/tf2-ch-c-security.adoc
=> Clarified security versus cybersecurity in Volume 2 Appendix C

CHANGELOG.md, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-b-ref-standards-conformance.adoc
Apply resolution for [HL7 2025-Jan: Clarification on ACNS 5.1 - New device is connected to network with AGW service](https://github.com/IHE/DEV.SDPi/issues/368)
Language added to the SDPi-A SES section indicating that risk management including DAS timing requirements and clinical usability must be addressed.
* [X ] Pull Request Assignee
* [X ] Reviewer
=> HL7 2025-Jan: Clarification on ACNS 5.1 - Added SES discussion for SDPi-A risk management section

CHANGELOG.md, asciidoc/listings/vol2-clause-appendix-a-mdpws-dev-29-descriptionmodificationreport.xml, asciidoc/listings/vol2-clause-appendix-a-mdpws-dev-29-operationalstatereport.xml, asciidoc/plantuml/vol2-figure-dev-29-sequence.puml, asciidoc/volume2/dev-29/tf2-ch-a-mdpws-dev-29.adoc, asciidoc/volume2/dev-29/tf2-dev-29-summary.adoc, asciidoc/volume2/dev-29/tf2-dev-29.adoc
=> 403 description reports and operational state reports missing in transactions

CHANGELOG.md, asciidoc/sdpi-supplement-intro.adoc, asciidoc/sdpi-supplement.adoc
=> Changes to wrap up release 2.1.0

CHANGELOG.md, asciidoc/plantuml/vol2-figure-dev-29-sequence.puml, asciidoc/sdpi-supplement.adoc, asciidoc/volume2/dev-29/tf2-ch-a-mdpws-dev-29.adoc
=> 441 fix findings from 210 review of dev 29

CHANGELOG.md, asciidoc/sdpi-supplement.adoc
Please verify if the new version and dates are correct.
=> build: version bump to 2.1.2.

CHANGELOG.md, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc
=> 464 note 2 of table 1121 1 may be incorrect

.github/prepare_artifacts.sh, .github/workflows/feature-review-build.yml, .github/workflows/latest-master-build.yml, .github/workflows/release-build.yml, CHANGELOG.md, asciidoc/plantuml/vol1-figure-sdpi-p-example-sequence-diagram.puml, asciidoc/plantuml/vol2-figure-dev-35-sequence.puml, asciidoc/plantuml/vol2-figure-dev-36-sequence.puml, asciidoc/plantuml/vol2-figure-dev-37-sequence.puml, asciidoc/plantuml/vol2-figure-dev-38-sequence.puml, asciidoc/plantuml/vol2-figure-dev-39-sequence.puml, asciidoc/plantuml/vol2-figure-dev-40-sequence.puml, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc
=> fix: #472 add asciidoctor-diagram-plantuml gem to artifacts handling.

.ci/asciidoc-converter/src/main/kotlin/org/sdpi/asciidoc/extension/ReferenceSanitizerPostprocessor.kt, CHANGELOG.md, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-a-requirements-interoperability.adoc
=> fix: #453 correctly display appendix and figure references

CHANGELOG.md, asciidoc/sdpi-supplement.adoc
=> removed statement on PDF availability

CHANGELOG.md, asciidoc/volume1/tf1-ch-10-sdpi-p.adoc, asciidoc/volume1/tf1-ch-11-sdpi-r.adoc, asciidoc/volume1/tf1-ch-12-sdpi-a.adoc, asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc, asciidoc/volume1/tf1-ch-2-overview.adoc, asciidoc/volume2/dev-34/tf2-ch-a-mdpws-dev-34.adoc, asciidoc/volume2/dev-34/tf2-dev-34.adoc
=> reviewed all Supplement Notes and updated some

CHANGELOG.md, asciidoc/sdpi-supplement-intro.adoc, asciidoc/sdpi-supplement.adoc, asciidoc/volume0/tf0-ch-b-transactions.adoc, asciidoc/volume3/biceps-extension-provisions/tf3-ch-a-xml-schemas-timestamp-version.adoc
=> SDPi 2.2 release cleanup
